### PR TITLE
update to 73.4.118

### PR DESCRIPTION
**Pull request by cho2**
update to 73.4.118

### CODE REVIEW

**Comment by cho2** [comment]
@wjt

**Comment by wjt** [comment]
@cho2 are you generating these by hand? I have a program which warns me about these https://github.com/endlessm/flatpak-external-data-checker and I'm working on automating PR creation :)

**Comment by cho2** [comment]
> @cho2 are you generating these by hand? 

Yes 

> I have a program which warns me about these https://github.com/endlessm/flatpak-external-data-checker and I'm working on automating PR creation :)

Cool, can't wait for automating this.

**Comment by cho2** [comment]
@wjt is https://github.com/endlessm/flatpak-external-data-checker only works on debian-based?

```
./flatpak-external-data-checker ~/com.dropbox.Client/com.dropbox.Client.json 
Traceback (most recent call last):
  File "./flatpak-external-data-checker", line 30, in <module>
    import checker
  File "/home/cho2/flatpak-external-data-checker/src/checker.py", line 21, in <module>
    from checkers import ALL_CHECKERS
  File "/home/cho2/flatpak-external-data-checker/src/checkers/__init__.py", line 1, in <module>
    from .debianrepochecker import DebianRepoChecker
  File "/home/cho2/flatpak-external-data-checker/src/checkers/debianrepochecker.py", line 33, in <module>
    import apt
ModuleNotFoundError: No module named 'apt'
```

**Comment by wjt** [comment]
It depends on http://packages.debian.org/python3-apt to check packages which fetch the relevant file from an apt repo, eg https://github.com/endlessm/eos-google-chrome-app/blob/master/com.google.Chrome.json#L68

**Pull request merged**
